### ISSUE TITLE
Are Modulation modes limited to llrp_proto.Modulation_Name2Type?

### ISSUE THREAD

**Issue by djacobson** [ransford/sllurp#114]
In llrp_proto, I can choose from the following modulation modes:

Modulation_Name2Type = {
    'FM0': 0,
    'M2': 1,
    'M4': 2,
    'M8': 3,
    'WISP5pre': 0,
    'WISP5': 0,
}

But, the Impinj R420 supports a "Max Miller" mode (value 4) that I'd like to use. Can I set this with the current sllurp version (i.e.: bypass this name dict)?

The supported Impinj modulation modes are documented here:

https://support.impinj.com/hc/en-us/articles/360000046899-Reader-Modes-Made-Easy

**Comment by djacobson** [comment]
Oh, is this what `--mode-identifier N` is meant for? Does it support more of the reader's modes than `--modulation`?

**Comment by thijmenketel** [comment]
As far as I know that would work as mode identifier will override other modulation settings I think. The implementation is a little unclear, but I maybe @ransford can tell you more.

**Comment by djacobson** [comment]
Ok, thanks. It's unclear to me if the mode-identifier number matches the mode number in the Impinj table in the linked page above. It looks like it. I'll test, hopefully the log will will be clear. :)

**Comment by djacobson** [comment]
I'm also testing using the '1003 = AutoSet Static Fast' mode. The log file  reports some interesting values when I give it 1003 for --mode-identifier, but, I think it's working... I'll upload the log output shortly when I get my hands back on the reader.

**Comment by ransford** [comment]
Mode selection is not great in sllurp because that part grew through accretion; early users wanted to control all the parameters (like Tari, modulation, mode identifier) individually, so we ended up with a weird thicket of logic in `LLRPClient.parseCapabilities()`.

If you start following the code [here](https://github.com/ransford/sllurp/blob/develop/sllurp/llrp.py#L366), here's what you'll see:
- If mode identifier is specified (on the command line), check the provided value against the list of mode identifiers the reader listed in its `RegulatoryCapabilities > UHFBandCapabilities > UHFRFModeTable`.
- If mode identifier isn't specified but modulation is (e.g., `M4`), consult `llrp_proto.Modulation_Name2Type` (worst name, I know) to find the corresponding mode identifier. The values in there happen to correspond to the table in Impinj's "reader modes made easy" [guide](https://support.impinj.com/hc/en-us/articles/360000046899-Reader-Modes-Made-Easy) that you found. This is probably the confusing part, as it was meant to be a shortcut so that [WISP](https://github.com/wisp/wisp5) developers could say "use the WISP-compatible modulation scheme" without having to figure out which mode identifier to use.
- If neither mode identifier nor modulation is specified but Tari is, do some checking of the provided Tari value but don't set it (!). As far as I can tell, this check will always fail because the `self.reader_mode` isn't yet set when this part is executed.

I think the best path forward is to remove the ability to choose a mode identifier from a provided modulation value, since it's confusing. Let me see what I can do to simplify the situation here.

**Comment by ransford** [comment]
@djacobson if you check out the `feature/114-simplify-mode-selection` branch, I hope you'll find mode selection more straightforward. I did what I suggested above. Does it work for you?

I'd love to see log output if you're seeing strange behavior with mode 1003. The reader I have at hand supports only {2, 3, 1000}.

**Comment by djacobson** [comment]
Thank you @ransford ! I will try that branch out this coming week. In the mean time, below is the sllurp log output I get when using mode identifier 1003. I thought it was doing what I desired, using the Impinj's "AutoSet Static Fast" mode, but, ?? Anyways, does the log output provide any insight?

David J.

2018-12-30 01:43:14.876 [sllurp.llrp]: INFO: connecting to speedwayr-10-3f-8d:5084...
2018-12-30 01:43:15.640 [sllurp.llrp]: INFO: will reset reader state on connect
2018-12-30 01:43:15.641 [sllurp.llrp]: INFO: will start inventory on connect
2018-12-30 01:43:15.642 [sllurp.llrp]: INFO: using antennas: [1, 2, 3, 4]
2018-12-30 01:43:15.645 [sllurp.llrp]: INFO: transmit power: {1: 0, 2: 0, 3: 0, 4: 0}
2018-12-30 01:43:15.655 [sllurp.llrp]: INFO: connected to ('speedwayr-10-3f-8d', 5084) (10.0.0.2:5084)
2018-12-30 01:43:19.372 [sllurp.llrp]: INFO: using reader mode: {'Mod': 0, 'FLM': 0, 'R': 0, 'M': 0, 'ModeIdentifier': 1003, 'PIE': 1500, 'BDR': 40000, 'MaxTari': 6250, 'MinTari': 6250, 'C': 0, 'StepTari': 0}

**Comment by ransford** [comment]
Looks to me like you successfully chose mode 1003. Good!
