### ISSUE TITLE
how to read data from sensormatic IDX-2000?

### ISSUE THREAD

**Issue by crssulton** [ransford/sllurp#148]

**Comment by crssulton** [comment]
![image](https://user-images.githubusercontent.com/49203342/70120322-e3294d00-169e-11ea-9212-dc1a488ad380.png)
I can connect, but how do I get the data?

**Comment by ransford** [comment]
The `inventory` command is just for demonstration purposes. If you run `sllurp inventory -n1 192.168.200.110:21`, do you see tag reports?

(Also, 21 is a strange port for LLRP -- 5084 is the standard port -- but maybe you have your reader configured differently.)

**Comment by crssulton** [comment]
Oh I understand. but, when I try again and find a new error.. how with this?

**Comment by crssulton** [comment]
![image](https://user-images.githubusercontent.com/49203342/71459691-3e041f00-27db-11ea-9e2f-3f155be2ba9a.png)

**Comment by ransford** [comment]
What revision of sllurp? `git describe --always` in the sllurp directory will tell you what version you are using.

**Comment by avasygn** [comment]
Hello @crssulton,

Maybe your reader does not respect LLRP strictly because the error occurs when sllurp try to decode a reader response. In my case, I cannot use sllurp with Kathrein reader although it should be compliant with LLRP. But I can drive Kathrein reader from the software of the manufacturer (which seems uses LLRP).

Try to run Wireshark to know more about the response of the reader which lead to an error.

**Comment by crssulton** [comment]
> Hello @crssulton,
> 
> Maybe your reader does not respect LLRP strictly because the error occurs when sllurp try to decode a reader response. In my case, I cannot use sllurp with Kathrein reader although it should be compliant with LLRP. But I can drive Kathrein reader from the software of the manufacturer (which seems uses LLRP).
> 
> Try to run Wireshark to know more about the response of the reader which lead to an error.

thanks you

**Comment by seba30** [comment]
Maybe see #160?
